import { prisma } from "./prisma";
import chalk from "chalk";

(async (): Promise<void> => {
  async function seedReaders() {
    // Gera 15 leitores no sistema
    await prisma.readers.createMany({
      data: [
        {
          email: "ana.silva@email.com",
          name: "Ana Silva",
          phone: "11987654321",
          bio: "Apaixonada por romances históricos e ficção científica. Lê um livro por semana.",
        },
        {
          email: "bruno.santos@email.com",
          name: "Bruno Santos",
          phone: "21976543210",
          bio: "Estudante de história, focado em biografias e livros técnicos de geopolítica.",
        },
        {
          email: "carla.oliveira@email.com",
          name: "Carla Oliveira",
          phone: "31965432109",
        },
        {
          email: "diego.souza@email.com",
          name: "Diego Souza",
          phone: "41954321098",
          bio: "Interessado em desenvolvimento pessoal, finanças e tecnologia.",
        },
        {
          email: "elena.ribeiro@email.com",
          name: "Elena Ribeiro",
          phone: "51943210987",
        },
        {
          email: "fernando.lima@email.com",
          name: "Fernando Lima",
          phone: "61932109876",
          bio: "Entusiasta de fantasia épica e RPG. Colecionador de sagas completas.",
        },
        {
          email: "gabriela.costa@email.com",
          name: "Gabriela Costa",
          phone: "71921098765",
          bio: "Professora de literatura infantil. Busca sempre novas obras infanto-juvenis.",
        },
        {
          email: "hugo.almeida@email.com",
          name: "Hugo Almeida",
          phone: "81910987654",
        },
        {
          email: "isabela.martins@email.com",
          name: "Isabela Martins",
          phone: "85909876543",
        },
        {
          email: "joao.pereira@email.com",
          name: "João Pereira",
          phone: "98998765432",
          bio: "Leitor assíduo de filosofia e sociologia. Sempre com um olho nos clássicos.",
        },
        {
          email: "larissa.gomes@email.com",
          name: "Larissa Gomes",
          phone: "19987652345",
          bio: "Fã de romances de época e comédias românticas leves para descontrair.",
        },
        {
          email: "marcos.rodrigues@email.com",
          name: "Marcos Rodrigues",
          phone: "27976541234",
          bio: "Gosta de livros sobre true crime, investigações reais e mistérios não resolvidos.",
        },
        {
          email: "natalia.carvalho@email.com",
          name: "Natália Carvalho",
          phone: "32965439876",
          bio: "Arquiteta que adora livros sobre arte, design, fotografia e urbanismo.",
        },
        {
          email: "otavio.mendes@email.com",
          name: "Otávio Mendes",
          phone: "47954328765",
        },
        {
          email: "patricia.antunes@email.com",
          name: "Patrícia Antunes",
          phone: "54943217654",
          bio: "Psicóloga clínica, lê muito sobre comportamento humano e neurociência.",
        },
        {
          email: "rafael.barros@email.com",
          name: "Rafael Barros",
          phone: "62932106543",
          bio: "Aventureiro que prefere relatos de viagem, guias de trilha e biografias de exploradores.",
        },
        {
          email: "sabrina.farias@email.com",
          name: "Sabrina Farias",
          phone: "79921095432",
          bio: "Escreve resenhas de livros na internet. Lê de tudo um pouco, sem preconceitos.",
        },
        {
          email: "thiago.nunes@email.com",
          name: "Thiago Nunes",
          phone: "84910984321",
          bio: "Engenheiro focado em leitura técnica, mas que relaxa lendo fantasia sombria.",
        },
        {
          email: "vanessa.moraes@email.com",
          name: "Vanessa Moraes",
          phone: "91909873210",
        },
        {
          email: "vitor.correia@email.com",
          name: "Vitor Correia",
          phone: "16998761234",
          bio: "Estuda línguas estrangeiras e costuma pegar livros em inglês e espanhol para praticar.",
        },
      ],
    });
  }

  async function seedBooks() {
    // Gera 30 livros no banco de dados
    await prisma.books.createMany({
      data: [
        {
          title: "O Alquimista",
          ISBN: "9788575427583",
          author: "Paulo Coelho",
          publisher: "Editora Sextante",
          year: "1988",
          category: ["Ficção", "Literatura Brasileira", "Filosofia"],
          availableQuantity: 5,
        },
        {
          title: "Dom Casmurro",
          ISBN: "9788520932582",
          author: "Machado de Assis",
          publisher: "Nova Fronteira",
          year: "1899",
          category: ["Clássicos", "Literatura Brasileira", "Romance"],
          availableQuantity: 3,
        },
        {
          title: "1984",
          ISBN: "9788535914849",
          author: "George Orwell",
          publisher: "Companhia das Letras",
          year: "1949",
          category: ["Ficção Científica", "Distopia", "Política"],
          availableQuantity: 7,
        },
        {
          title: "O Hobbit",
          ISBN: "9788595084742",
          author: "J.R.R. Tolkien",
          publisher: "HarperCollins",
          year: "1937",
          category: ["Fantasia", "Aventura"],
          availableQuantity: 4,
        },
        {
          title: "Sapiens: Uma Breve História da Humanidade",
          ISBN: "9788525432187",
          author: "Yuval Noah Harari",
          publisher: "L&PM Editores",
          year: "2011",
          category: ["História", "Não-Ficção", "Antropologia"],
          availableQuantity: 6,
        },
        {
          title: "A Garota no Trem",
          ISBN: "9788501104618",
          author: "Paula Hawkins",
          publisher: "Editora Record",
          year: "2015",
          category: ["Suspense", "Thriller", "Mistério"],
          availableQuantity: 4,
        },
        {
          title: "O Homem Mais Rico da Babilônia",
          ISBN: "9788575422571",
          author: "George S. Clason",
          publisher: "Editora Sextante",
          year: "1926",
          category: ["Finanças", "Desenvolvimento Pessoal"],
          availableQuantity: 8,
        },
        {
          title: "Harry Potter e a Pedra Filosofal",
          ISBN: "9788532511010",
          author: "J.K. Rowling",
          publisher: "Rocco",
          year: "1997",
          category: ["Fantasia", "Infanto-Juvenil"],
          availableQuantity: 10,
        },
        {
          title: "Cem Anos de Solidão",
          ISBN: "9788501012074",
          author: "Gabriel García Márquez",
          publisher: "Editora Record",
          year: "1967",
          category: ["Realismo Mágico", "Clássicos", "Literatura Latina"],
          availableQuantity: 3,
        },
        {
          title: "O Poder do Hábito",
          ISBN: "9788511002263",
          author: "Charles Duhigg",
          publisher: "Objetiva",
          year: "2012",
          category: ["Psicologia", "Desenvolvimento Pessoal", "Produtividade"],
          availableQuantity: 5,
        },
        {
          title: "Orgulho e Preconceito",
          ISBN: "9788525416491",
          author: "Jane Austen",
          publisher: "L&PM Editores",
          year: "1813",
          category: ["Clássicos", "Romance", "Drama"],
          availableQuantity: 4,
        },
        {
          title: "Duna",
          ISBN: "9788576573005",
          author: "Frank Herbert",
          publisher: "Editora Aleph",
          year: "1965",
          category: ["Ficção Científica", "Épico"],
          availableQuantity: 6,
        },
        {
          title: "A Culpa é das Estrelas",
          ISBN: "9788580572261",
          author: "John Green",
          publisher: "Intrínseca",
          year: "2012",
          category: ["Romance", "Jovem Adulto", "Drama"],
          availableQuantity: 5,
        },
        {
          title: "Flores para Algernon",
          ISBN: "9788576574347",
          author: "Daniel Keyes",
          publisher: "Editora Aleph",
          year: "1966",
          category: ["Ficção Científica", "Drama", "Psicologia"],
          availableQuantity: 3,
        },
        {
          title: "O Código Da Vinci",
          ISBN: "9788575420911",
          author: "Dan Brown",
          publisher: "Editora Sextante",
          year: "2003",
          category: ["Suspense", "Mistério", "Ficção"],
          availableQuantity: 6,
        },
        {
          title: "A Revolução dos Bichos",
          ISBN: "9788535909555",
          author: "George Orwell",
          publisher: "Companhia das Letras",
          year: "1945",
          category: ["Clássicos", "Sátira", "Política"],
          availableQuantity: 8,
        },
        {
          title: "Corte de Espinhos e Rosas",
          ISBN: "9788501105837",
          author: "Sarah J. Maas",
          publisher: "Galera Record",
          year: "2015",
          category: ["Fantasia", "Romance", "New Adult"],
          availableQuantity: 5,
        },
        {
          title: "Rápido e Devagar: Duas Formas de Pensar",
          ISBN: "9788511002539",
          author: "Daniel Kahneman",
          publisher: "Objetiva",
          year: "2011",
          category: ["Psicologia", "Economia", "Não-Ficção"],
          availableQuantity: 4,
        },
        {
          title: "Pai Rico, Pai Pobre",
          ISBN: "9788535287660",
          author: "Robert T. Kiyosaki",
          publisher: "Alta Books",
          year: "1997",
          category: ["Finanças", "Negócios", "Educação"],
          availableQuantity: 9,
        },
        {
          title: "O Iluminado",
          ISBN: "9788539304165",
          author: "Stephen King",
          publisher: "Suma",
          year: "1977",
          category: ["Terror", "Suspense", "Sobrenatural"],
          availableQuantity: 4,
        },
        {
          title: "Grandes Esperanças",
          ISBN: "9788535921861",
          author: "Charles Dickens",
          publisher: "Companhia das Letras",
          year: "1861",
          category: ["Clássicos", "Literatura Estrangeira"],
          availableQuantity: 2,
        },
        {
          title: "Torto Arado",
          ISBN: "9788535932485",
          author: "Itamar Vieira Junior",
          publisher: "Companhia das Letras",
          year: "2019",
          category: ["Literatura Brasileira", "Drama", "Ficção"],
          availableQuantity: 7,
        },
        {
          title: "O Sol é Para Todos",
          ISBN: "9788501046833",
          author: "Harper Lee",
          publisher: "José Olympio",
          year: "1960",
          category: ["Clássicos", "Drama", "Justiça"],
          availableQuantity: 5,
        },
        {
          title: "A Sutil Arte de Ligar o F*da-se",
          ISBN: "9788551002490",
          author: "Mark Manson",
          publisher: "Intrínseca",
          year: "2016",
          category: ["Autoajuda", "Desenvolvimento Pessoal"],
          availableQuantity: 11,
        },
        {
          title: "Coraline",
          ISBN: "9788580575309",
          author: "Neil Gaiman",
          publisher: "Intrínseca",
          year: "2002",
          category: ["Fantasia", "Terror Infanto-Juvenil", "Mistério"],
          availableQuantity: 6,
        },
        {
          title: "O Diário de Anne Frank",
          ISBN: "9788501044457",
          author: "Anne Frank",
          publisher: "Editora Record",
          year: "1947",
          category: ["Biografia", "História", "Não-Ficção"],
          availableQuantity: 5,
        },
        {
          title: "Neuromancer",
          ISBN: "9788576573012",
          author: "William Gibson",
          publisher: "Editora Aleph",
          year: "1984",
          category: ["Ficção Científica", "Cyberpunk"],
          availableQuantity: 3,
        },
        {
          title: "Coração de Tinta",
          ISBN: "9788535907407",
          author: "Cornelia Funke",
          publisher: "Companhia das Letrinhas",
          year: "2003",
          category: ["Fantasia", "Aventura", "Juvenil"],
          availableQuantity: 4,
        },
        {
          title: "Gente Ansiosa",
          ISBN: "9786555601954",
          author: "Fredrik Backman",
          publisher: "Intrínseca",
          year: "2019",
          category: ["Ficção", "Drama", "Comédia"],
          availableQuantity: 5,
        },
        {
          title: "O Silêncio dos Inocentes",
          ISBN: "9788501037671",
          author: "Thomas Harris",
          publisher: "Editora Record",
          year: "1988",
          category: ["Thriller", "Suspense", "Policial"],
          availableQuantity: 4,
        },
      ],
    });
  }

  await seedReaders();
  console.log(chalk.bgGreen.bold.black("  [SEED] READERS SUCESSO!  "));
  await seedBooks();
  console.log(chalk.bgGreen.bold.black("  [SEED] BOOKS SUCESSO!  "));
})();
